// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKK3ebn-bJrSW-htSgGI8w93d_fp1VgYE',
    appId: '1:559758606438:web:44a46d8a4c8cfe11cd6da7',
    messagingSenderId: '559758606438',
    projectId: 'login-page-5d51b',
    authDomain: 'login-page-5d51b.firebaseapp.com',
    storageBucket: 'login-page-5d51b.appspot.com',
    measurementId: 'G-PE9BNQSC4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzn4207lZwdiJWM08_zfoW_ivn7RVCgnk',
    appId: '1:559758606438:android:deda8d883abd2f63cd6da7',
    messagingSenderId: '559758606438',
    projectId: 'login-page-5d51b',
    storageBucket: 'login-page-5d51b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVMwkQh94TIYQ_t4WiNTx7MHtTwAHRrWw',
    appId: '1:559758606438:ios:efda03e2dea4ddcbcd6da7',
    messagingSenderId: '559758606438',
    projectId: 'login-page-5d51b',
    storageBucket: 'login-page-5d51b.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVMwkQh94TIYQ_t4WiNTx7MHtTwAHRrWw',
    appId: '1:559758606438:ios:efda03e2dea4ddcbcd6da7',
    messagingSenderId: '559758606438',
    projectId: 'login-page-5d51b',
    storageBucket: 'login-page-5d51b.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKK3ebn-bJrSW-htSgGI8w93d_fp1VgYE',
    appId: '1:559758606438:web:20bb3c02177af8c1cd6da7',
    messagingSenderId: '559758606438',
    projectId: 'login-page-5d51b',
    authDomain: 'login-page-5d51b.firebaseapp.com',
    storageBucket: 'login-page-5d51b.appspot.com',
    measurementId: 'G-P73GGL8D1T',
  );
}
